[terminal]
vt = 1

[default_session]
command = "sway --config /etc/greetd/swayconfig > /dev/null 2>&1"
user = "greeter"

[initial_session]
command = "sway"
user = "eshanized"

[General]
Background = /usr/share/wallpapers/eshanizedos-wallpapers/01.jpg
BaseColor = ffffffff
TextColor = ffffff
